services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: rogerbacon
    #     user: 501:0
    #     network_mode: 'host'
    volumes:
      - /Users/kees/Workstation/Jellyfin/Config:/config
      - /Users/kees/Workstation/Jellyfin/Cache:/cache
      - type: bind
        source: /Users/kees/Workstation/Jellyfin/Media
        target: /media
    ports:
      - 8096:8096
      - 8920:8920
    restart: "unless-stopped"
  #      Optional - alternative address used for autodiscovery
  #      environment:
  #       - JELLYFIN_PublishedServerUrl=http://example.com
  #      Optional - may be necessary for docker healthcheck to pass if running in host network mode
  #     extra_hosts:
  #       - 'host.docker.internal:host-gateway'
  caddy:
    image: caddy:2-alpine
    container_name: rogerbacon-caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /Users/kees/Workstation/Jellyfin/Caddy/Caddyfile:/etc/caddy/Caddyfile
      - /Users/kees/Workstation/Jellyfin/Caddy/data:/data
      - /Users/kees/Workstation/Jellyfin/Caddy/config:/config
